# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ST10445832_PROG6221_Part1.sln
      
    - name: Build
      run: dotnet build ST10445832_PROG6221_Part1.sln --no-restore
      
    - name: Test
      run: dotnet test ST10445832_PROG6221_Part1.sln --no-build --verbosity normal
      
      # ChatGPT
    - name: Check Formatting
      run: dotnet format --verify-no-changes --severity error
      # End ChatGPT
