name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x' # <--- CRITICAL: Set this to your exact .NET version, e.g., '6.0.x', '7.0.x', '8.0.x'
                              # Using a specific patch version like '8.0.1' might be safer than '8.x' if issues persist.

    - name: Verify dotnet CLI is on PATH
      run: |
        echo "PATH: %PATH%"
        dotnet --version
        where msbuild # On Windows, 'where' is like 'which' on Linux/macOS

    - name: Restore NuGet packages
      # For SDK-style projects, 'dotnet restore' is generally preferred and often implicitly run by 'dotnet build'.
      # If your project uses packages.config, 'nuget restore' is correct.
      run: nuget restore ST10445832_PROG6221_PoE.sln

    - name: Build with MSBuild
      # For SDK-style projects, consider using 'dotnet build' as it wraps MSBuild and handles the SDK setup better.
      # If your project is not SDK-style, keep msbuild directly.
      run: msbuild ST10445832_PROG6221_PoE.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Check Formatting
      run: dotnet format ST10445832_PROG6221_PoE.sln --verify-no-changes --severity error
