# Written with Gemini
name: Build and Validate Code Formatting

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-format:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild and NuGet
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      shell: pwsh
      run: nuget restore ST10445832_PROG6221_PoE.sln

    - name: Build application
      shell: pwsh
      run: msbuild ST10445832_PROG6221_PoE.sln /p:Configuration=Release /p:Platform="Any CPU" /t:Rebuild

    - name: Setup .NET SDK for dotnet format
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Use a recent .NET SDK version

    - name: Check code format
      run: dotnet format ST10445832_PROG6221_PoE.sln --verify-no-changes
